language: python
python: '3.6'
sudo: required
dist: trusty
install:
- pip install --upgrade pip wheel setuptools
- pip install virtualenv tox
before_script:
- sh -c "if [ '$DATABASE_ENGINE' = 'pgsql' ]; then psql -c 'DROP DATABASE IF EXISTS
  tagulous_tests;' -U postgres; fi"
- sh -c "if [ '$DATABASE_ENGINE' = 'pgsql' ]; then psql -c 'create database tagulous_tests;'
  -U postgres; fi"
- sh -c "if [ '$DATABASE_ENGINE' = 'mysql' ]; then mysql -e 'create database IF NOT
  EXISTS tagulous_tests'; fi"
script:
- tox
env:
  matrix:
  - TOXENV=py27-django1.5
  - TOXENV=py27-django1.6
  - TOXENV=py27-django1.7
  - TOXENV=py34-django1.7
  - TOXENV=py27-django1.8
  - TOXENV=py27-django1.8 DATABASE_ENGINE=mysql DATABASE_USER=travis
  - TOXENV=py27-django1.8 DATABASE_ENGINE=pgsql DATABASE_USER=postgres
  - TOXENV=py34-django1.8
  - TOXENV=py34-django1.8 DATABASE_ENGINE=mysql DATABASE_USER=travis
  - TOXENV=py34-django1.8 DATABASE_ENGINE=pgsql DATABASE_USER=postgres
  - TOXENV=py27-django1.9
  - TOXENV=py34-django1.9
  - TOXENV=py35-django1.9
  - TOXENV=py27-django1.10
  - TOXENV=py34-django1.10
  - TOXENV=py35-django1.10
  - TOXENV=py27-django1.11
  - TOXENV=py34-django1.11
  - TOXENV=py35-django1.11
  - TOXENV=py36-django1.11
  - TOXENV=py27-django1.11 DATABASE_ENGINE=mysql DATABASE_USER=travis
  - TOXENV=py27-django1.11 DATABASE_ENGINE=pgsql DATABASE_USER=postgres
  - TOXENV=py36-django1.11 DATABASE_ENGINE=mysql DATABASE_USER=travis
  - TOXENV=py36-django1.11 DATABASE_ENGINE=pgsql DATABASE_USER=postgres
matrix:
  include:
  - python: '3.5'
    env: TOXENV=py35-django1.9
  - python: '3.5'
    env: TOXENV=py35-django1.10
  - python: '3.5'
    env: TOXENV=py35-django1.11
  exclude:
  - python: '3.6'
    env: TOXENV=py35-django1.9
  - python: '3.6'
    env: TOXENV=py35-django1.10
  - python: '3.6'
    env: TOXENV=py35-django1.11
deploy:
  provider: pypi
  user: radiac
  password:
    secure: UlOAJbdXXcdNci9gcfpLLldDxQJNWzQMnaTlN29CyH4MWvP+F1dGl8yl7RffzIb805EKVMOi4tLY+oA3x6ZS/Lis1QjpOC8erqgU0pMEHtF3ghR9qcd75GLz25AaDiX8G7SXdSwyedS8m+lxaiemGganGMhIKsme2lQV20iticTI8gb9I4dYBnSKcG8MfLcsU91usFyhadOP5EHqooG4+p+cF36Vk8ff0hW53/gttXrMoDs7zbfX7iJIXQPQp7fSg/g1KLgjcQQTNFSxpqCbqLPdFOKeCmhn2UlwIUWAxYHK3gNO2uyBiuAhle323AnB4ifWv+urG6Zw7712NPoJ53FVlxZ5+yf329aw2yCRFTgwfl4WV15ZWuvVgI//jUhlK47P/mjFb7RZjYu0c+9VqyzXccvXyuSM6fuyHQAzWYlz8Z26x5hSmAi5paQbGieoI5jOeWJ94YSUeWPRfW/7VVvx1nUztq8O2FNmMt3rYih1FiElWFpkSQ4WdEjXxbW6wgQL8v5PJy2puBS9jwTv7SrQ9aKAtwcxnn8U46+EKILuKdqalrRTIZbVthylaxl5yNO5To6z0Sou/mXQURvWUavGHAp05bRkr4XaL0ZWedivNSXsGQuHA8qmh5eiely4hr+6FMSBe8KvJv8JDryv+aCIHamTJjljU7AgEchIOrk=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: radiac/django-tagulous
    condition: '$TOXENV = py36-django1.11'
